---
name: Graphics-ColorNames-Crayola
version: 1.00
author:
  - 'Robert Rothenberg <rrwo at cpan.org>'
abstract: the original 48 crayola crayon colors
license: unrestricted
requires:
  Graphics::ColorNames: 1.01
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Graphics::ColorNames::Crayola:
    file: lib/Graphics/ColorNames/Crayola.pm
    version: 1.00
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
